### ISSUE TITLE
Use ordered arrays instead of maps

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint-ast#1]
Proposed change as posted originally at apiaryio/snowcrash#60: 
## Use ordered arrays instead of maps

In order to preserver ordering of headers, metadata and parameter keys in various settings and languages the following changes are needed:
- **Metadata object** use ordered array instead of a map
- **Headers object** use ordered array instead of a map
- **Parameters object** use ordered array instead of a map 

From (v1.0):

``` yaml
metadata:
  <key>:
    value: <value>
```

To (v2.0):

``` yaml
metadata: 
- name: "<metadata key name>"
  value: "<metadata value>"
```

From (v1.0):

``` json
"metadata": {
  "<key>": {
    "value": "<value>"
  }
},
```

To (v2.0):

``` json
"metadata": [
  {
    "name": "<metadata key name>",
    "value": "<metadata value>"
  }
],
```

**Same change applies to headers and parameters objects.**

Up to this point this change does **affects serialized AST media types only**. It does not affect the actual AST structure as defined and used within the Snow Crash.
