### ISSUE TITLE
Use object for parameter values

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint-ast#3]
For a possible future development a serialized parameter value entry should be an object (hash) instead of just a textual value. 

E.g.: 

From (v1.0): 

``` yaml
    parameters: 
      - name: "<name>"
        description: "<description>"
        type: "<type>"
        required: "<required parameter flag>"
        default: "<default value>"
        example: "<example value>"
        values: 
          - "<element>"
```

To (v2.0):

``` yaml
    parameters: 
      - name: "<name>"
        description: "<description>"
        type: "<type>"
        required: "<required parameter flag>"
        default: "<default value>"
        example: "<example value>"
        values: 
          - value: "<enum element>"
```

This will enable future non-breakign changes in values enumeration format such as adding description of an enum element.
